### ISSUE TITLE
[FEAT] Implementar Tela de Cadastro e Log In

### ISSUE THREAD

**Issue by Frotas** [Frotas/atividade_agencia_de_viagens#2]
# Implementação da Tela de Cadastro:

Implementação da tela de cadastro de usuários.

## Tasks:

- [ ] Sign In e Sign Up
   - [ ] Prototipação das paginas no [FIGMA](https://figma.com/)
   - [ ] Implementação da Pagina de Cadastro (HTML/CSS/JS)
     - [ ] HTML
       - [ ] Formulário
     - [ ] CSS/SCSS
        - [ ] Re-Estilização do Bootstrap
          - [ ] Caixa de Texto
          - [ ] Botões
     - [ ] JS 
        - [ ] Validação dos Dados
          - [ ] Cadastro
          - [ ] Log In
