### ISSUE TITLE
[FEAT] Implementar Tela de Vendas

### ISSUE THREAD

**Issue by Frotas** [Frotas/atividade_agencia_de_viagens#3]
# Implementação da Tela de Vendas:

Implementação da tela de vendas, Opções de Pagamentos e Gerador de Carne, Validação de Cartão de Crédito via API.

## Tasks:

- [ ] Selling
   - [ ] Prototipação da pagina no [FIGMA](https://figma.com/)
   - [ ] Implementação da Pagina de Vendas (HTML/CSS/JS)
     - [ ] HTML
       - [ ] Lista de Produtos
         - [ ] Cards
       - [ ] Formulário de Venda
          - [ ] Opção de Pagamento
            - [ ] Cartão de Crédito
            - [ ] Carne
     - [ ] CSS/SCSS
        - [ ] Re-Estilização do Bootstrap
          - [ ] Caixa de Texto
          - [ ] Botões
     - [ ] JS 
        - [ ] Validação dos Dados
          - [ ] Vendas
            - [ ] API Validador de Cartão de Crédito
            - [ ] [API Gerador de Carne](https://dev.gerencianet.com.br/docs/carnes-criando)
